// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLVYPgHrpPT2N2D5FTrWlTu1KfmeUHwZI',
    appId: '1:38111035694:web:42563bc6eb15041d3f3abf',
    messagingSenderId: '38111035694',
    projectId: 'lookout-22clc10-group01',
    authDomain: 'lookout-22clc10-group01.firebaseapp.com',
    storageBucket: 'lookout-22clc10-group01.appspot.com',
    measurementId: 'G-2WZEEVD3H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATJqgIor4DKdKfp0FqfHF9-E0Hs1fjfvE',
    appId: '1:38111035694:android:2cc5fd0f271bfae73f3abf',
    messagingSenderId: '38111035694',
    projectId: 'lookout-22clc10-group01',
    storageBucket: 'lookout-22clc10-group01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAFuooEIKGRDM278wvwGJhFTydkrdiHi8',
    appId: '1:38111035694:ios:f6cd211ab819d97c3f3abf',
    messagingSenderId: '38111035694',
    projectId: 'lookout-22clc10-group01',
    storageBucket: 'lookout-22clc10-group01.appspot.com',
    iosBundleId: 'com.example.lookoutDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAFuooEIKGRDM278wvwGJhFTydkrdiHi8',
    appId: '1:38111035694:ios:f6cd211ab819d97c3f3abf',
    messagingSenderId: '38111035694',
    projectId: 'lookout-22clc10-group01',
    storageBucket: 'lookout-22clc10-group01.appspot.com',
    iosBundleId: 'com.example.lookoutDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLVYPgHrpPT2N2D5FTrWlTu1KfmeUHwZI',
    appId: '1:38111035694:web:4a5ca1db22aa34dc3f3abf',
    messagingSenderId: '38111035694',
    projectId: 'lookout-22clc10-group01',
    authDomain: 'lookout-22clc10-group01.firebaseapp.com',
    storageBucket: 'lookout-22clc10-group01.appspot.com',
    measurementId: 'G-5LX1N7R680',
  );
}
